### ISSUE TITLE
ULTRA2.0: which flash goes with which file?

### ISSUE THREAD

**Issue by joelburton** [slu4coder/Minimal-UART-CPU-System#6] opened 2024-05-01 05:10 UTC
I've been assembling the v2 ULTRA of this, and am at the point of burning the flash chips to add them. Apologies if I'm missing something obvious, but I don't see which of U6/U12/U30 goes with which of the lsb/msb/hsb files. Any help would be appreciated!

(also: I've looked through the [very helpful!] docs, but those focus on v1.6 or before --- if I get this started up, what would the baud rate for the serial port be? 115200? Something else?)

Thanks, and thanks for all the videos and interesting designs, @slu4coder .

**Comment by slu4coder** [comment] 2024-05-01 06:22
Hi Joel,
you are building one of the old legacy versions of my CPU project. Please search for "Minimal 64x4" if you want to see the latest developments.
Please note that revision 2.0 was intended and released as a 'breadboard only' version to demonstrate higher clockrates (see my videos about it on YouTube). I appologize for any confusion about this matter. I only now realize that I actually included some PCB routing as part of the KiCAD project. I didn't publish any Gerber files or pictures of the layout, though. The PCB is untested and was never intended for release.

U6=HSB, U12=MSB, U30=LSB
UART bitrate = CPU clockrate / 16

Cheers!

**Comment by joelburton** [comment] 2024-05-01 06:34
Ah! I hadn't realized that. I also had some of your 64x4 boards made, but I was going to make this first since I assumed it would be a bit easier to debug given that it doesn't have VGA/keyboard in the circuit.

Thanks for the help — and I'll let you know if the design works :)

**Closed as completed** 2024-05-01 06:34 UTC
